var PUBLIC_CONFIG=window.APP_CONFIG||{},STORAGE_KEY="departureCompanionPrivateSettingsV1",ROUTINE_KEY="departureCompanionRoutinesV1",C={},lastDepartures=[],lastStationDiagnostics="";

function $(id){return document.getElementById(id)}
function readPrivateSettings(){try{var raw=localStorage.getItem(STORAGE_KEY);return raw?JSON.parse(raw):null}catch(e){return null}}
function savePrivateSettings(s){localStorage.setItem(STORAGE_KEY,JSON.stringify(s))}
function buildConfig(){C={};for(var k in PUBLIC_CONFIG)C[k]=PUBLIC_CONFIG[k];var local=readPrivateSettings();if(local){if(local.latitude)C.latitude=Number(local.latitude);if(local.longitude)C.longitude=Number(local.longitude);if(local.radiusMeters)C.radiusMeters=Number(local.radiusMeters);if(local.placeName)C.placeName=local.placeName;C.hasPrivateSettings=true}else C.hasPrivateSettings=false}
function showSetup(show){$("setupPanel").className=show?"setup":"setup hidden"}
function updateClock(){var n=new Date();$("time").textContent=n.toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"});$("date").textContent=n.toLocaleDateString([],{weekday:"long",day:"numeric",month:"long"})}
function round(n){return Math.round(n)}
function weatherIcon(c){if(c===0)return"☀️";if(c===1||c===2)return"🌤️";if(c===3)return"☁️";if(c>=45&&c<=48)return"🌫️";if(c>=51&&c<=67)return"🌦️";if(c>=71&&c<=77)return"❄️";if(c>=80&&c<=82)return"🌧️";if(c>=95)return"⛈️";return"☁️"}
function formatCountdown(ms){if(ms<0)ms=0;var total=Math.floor(ms/1000),m=Math.floor(total/60),s=total%60;return(m<10?"0":"")+m+":"+(s<10?"0":"")+s}
function lineLabel(d){var cat=(d.category||"").toLowerCase(),n=String(d.number||"");if(cat.indexOf("m")>=0||n.toLowerCase().indexOf("m")===0)return n.toLowerCase().indexOf("m")===0?n.toUpperCase():"M"+n;if(cat.indexOf("bus")>=0)return"Bus "+n;if(n)return(d.category+" "+n).trim();return d.category||"Transport"}
function isMetro(d){var c=(d.category||"").toLowerCase(),n=String(d.number||"").toLowerCase();return c.indexOf("m")>=0||n.indexOf("m")===0}
function isBus(d){var c=(d.category||"").toLowerCase();return c.indexOf("bus")>=0}
function priority(d){if(isMetro(d))return 1;var c=(d.category||"").toLowerCase();if(c.indexOf("train")>=0||c==="ir"||c==="ic"||c==="s")return 2;if(isBus(d))return 3;return 4}
function updateCountdowns(){var changed=false,nodes=document.querySelectorAll("[data-departure-ms]");for(var i=0;i<nodes.length;i++){var ms=Number(nodes[i].getAttribute("data-departure-ms"))-Date.now();nodes[i].textContent=formatCountdown(ms);if(ms<=0){var row=nodes[i].getAttribute("data-row-id");var el=document.querySelector('[data-row-wrapper="'+row+'"]');if(el&&el.className.indexOf("expiring")<0)el.className+=" expiring";changed=true}}if(changed){setTimeout(function(){lastDepartures=lastDepartures.filter(function(d){return d.departureMs>Date.now()});renderTransport(lastDepartures,true)},520)}}
function recommendation(h){var now=new Date(),times=h.time.map(function(t){return new Date(t)}),start=times.findIndex(function(t){return t>=now});if(start<0)start=0;var next=[];for(var i=start;i<Math.min(start+12,h.time.length);i++)next.push({time:h.time[i],temp:h.temperature_2m[i],rainProb:h.precipitation_probability[i]||0,precip:h.precipitation[i]||0,uv:h.uv_index?h.uv_index[i]:0,wind:h.wind_speed_10m?h.wind_speed_10m[i]:0});var rainy=next.find(function(x){return x.rainProb>=55||x.precip>=.3}),cold=next.find(function(x){return x.temp<=8}),hot=next.find(function(x){return x.temp>=28}),uv=next.find(function(x){return x.uv>=7}),windy=next.find(function(x){return x.wind>=35});if(rainy&&cold)return["☔🧥","Umbrella + coat","Rain and cold conditions expected"];if(rainy)return["☔","Take umbrella","Rain likely around "+rainy.time.slice(11,16)];if(cold)return["🧥","Take a coat","Cold conditions expected"];if(uv)return["🧴","Take sunscreen","High UV expected today"];if(hot)return["💧","Take water","High temperature expected"];if(windy)return["🌬️","Take windbreaker","Strong wind expected"];return["☀️","No special prep","Dry and mild conditions ahead"]}
async function fetchWeather(){var url="https://api.open-meteo.com/v1/forecast?latitude="+C.latitude+"&longitude="+C.longitude+"&current=temperature_2m,weather_code,wind_speed_10m&hourly=temperature_2m,precipitation_probability,precipitation,weather_code,uv_index,wind_speed_10m&daily=temperature_2m_max,temperature_2m_min&forecast_days=2&timezone=auto",r=await fetch(url);if(!r.ok)throw new Error("Weather API failed");return await r.json()}
function renderWeather(d){$("placeName").textContent=C.placeName||"Lausanne, Switzerland";var nowTemp=round(d.current.temperature_2m),wind=round(d.current.wind_speed_10m||0);$("miniTemp").textContent=nowTemp+"°C";$("miniIcon").textContent=weatherIcon(d.current.weather_code);$("tempNow").textContent=nowTemp+"°C";$("tempMax").textContent=round(d.daily.temperature_2m_max[0])+"°C";$("tempMin").textContent=round(d.daily.temperature_2m_min[0])+"°C";$("windLine").textContent="Wind: "+wind+" km/h";$("windMetric").textContent=wind+" km/h";var rec=recommendation(d.hourly);$("recommendationIcon").textContent=rec[0];$("recommendationTitle").textContent=rec[1];$("recommendationReason").textContent=rec[2];var now=new Date(),times=d.hourly.time.map(function(t){return new Date(t)}),start=times.findIndex(function(t){return t>=now});if(start<0)start=0;var html="";for(var s=0;s<C.forecastSlots;s++){var idx=start+s*C.forecastStepHours;if(idx>=d.hourly.time.length)break;var label=s===0?"Now":"+"+s*C.forecastStepHours+"h";html+="<div><b>"+label+"</b><span>"+weatherIcon(d.hourly.weather_code[idx])+"</span><strong>"+round(d.hourly.temperature_2m[idx])+"°C</strong><small>💧"+(d.hourly.precipitation_probability[idx]||0)+"%</small><em>🌬 "+round(d.hourly.wind_speed_10m[idx]||0)+" km/h</em></div>"}$("forecastSlots").innerHTML=html}
function stationLooksUsable(s){return s&&s.name&&s.name.length>1}
async function fetchLocationsWithRadius(radius){var url="https://transport.opendata.ch/v1/locations?x="+C.latitude+"&y="+C.longitude;var r=await fetch(url);if(!r.ok)throw new Error("Locations API failed");var d=await r.json();return(d.stations||[]).filter(stationLooksUsable).filter(function(s){return s.distance==null||s.distance<=radius}).sort(function(a,b){return(a.distance||999999)-(b.distance||999999)})}
async function fetchLocationsProgressive(){var radii=[Number(C.radiusMeters||700),1000,Number(C.maxStationSearchRadiusMeters||1500)];var seen={},chosen=[],usedRadius=radii[0];for(var ri=0;ri<radii.length;ri++){var radius=radii[ri],stations=await fetchLocationsWithRadius(radius);for(var i=0;i<stations.length;i++){var key=(stations[i].id||stations[i].name);if(!seen[key]){seen[key]=true;chosen.push(stations[i])}}if(chosen.length>=4){usedRadius=radius;break}usedRadius=radius}lastStationDiagnostics="stations: "+chosen.length+" within "+usedRadius+" m";return chosen.slice(0,8)}
async function fetchStationboard(station){var id=station.id||station.name,url="https://transport.opendata.ch/v1/stationboard?station="+encodeURIComponent(id)+"&limit=8",r=await fetch(url);if(!r.ok)throw new Error("Stationboard API failed");var d=await r.json();return(d.stationboard||[]).map(function(x){var dep=x.stop&&x.stop.departure,ms=dep?new Date(dep).getTime():null;return{stop:station.name,distance:station.distance||0,category:x.category||"",number:x.number||"",to:x.to||"",departure:dep,departureMs:ms}})}
function sortDepartures(deps){return deps.filter(function(d){return d.departureMs&&d.departureMs>=Date.now()-1000}).sort(function(a,b){return priority(a)-priority(b)||a.departureMs-b.departureMs||a.distance-b.distance})}
function sortByTime(deps){return deps.slice().sort(function(a,b){return a.departureMs-b.departureMs||a.distance-b.distance})}
function rowId(prefix,i){return prefix+"-"+i}
function renderTransport(deps,fromCache){deps=sortDepartures(deps);lastDepartures=deps;var useful=deps.slice(0,2);$("usefulTrips").innerHTML=useful.map(function(d,i){var isM=isMetro(d),id=rowId("useful",i);return'<div class="line" data-row-wrapper="'+id+'"><span class="badge '+(isM?"m":"b")+'">'+(d.number||d.category||"?")+'</span><p><b>'+lineLabel(d)+" · "+d.stop+"</b><br>"+Math.round(d.distance||0)+" m away → "+d.to+'</p><strong class="countdown '+(isM?"":"purple")+'" data-row-id="'+id+'" data-departure-ms="'+d.departureMs+'">--:--</strong></div><hr>'}).join("")||"No departures found";var metroHtml=sortByTime(deps.filter(isMetro)).slice(0,3),busHtml=sortByTime(deps.filter(isBus)).slice(0,3);function group(title,arr,prefix){return'<div class="group"><h2>'+title+"</h2>"+(arr.length?arr.map(function(d,i){var id=rowId(prefix,i);return'<div class="transport-row" data-row-wrapper="'+id+'"><p><b>'+lineLabel(d)+"</b> "+d.stop+'<br><small>→ '+d.to+'</small></p><div class="meta">'+Math.round(d.distance||0)+' m<span class="time" data-row-id="'+id+'" data-departure-ms="'+d.departureMs+'">--:--</span></div></div>'}).join(""):'<p><small>No departures found in this category.</small></p>')+"</div>"}$("nearbyTransport").innerHTML=group("🚇 Metro",metroHtml,"metro")+group("🚌 Bus",busHtml,"bus");$("favoriteDestinations").innerHTML=C.favoriteDestinations.map(function(f,i){var match=sortByTime(deps).find(function(d){return(d.to||"").toLowerCase().indexOf(f.match.toLowerCase())>=0});var id=rowId("dest",i);if(!match)return'<div class="dest"><span class="icon">'+f.icon+"</span><p><b>To "+f.name+"</b><br>No useful live departure found</p></div>";return'<div class="dest" data-row-wrapper="'+id+'"><span class="icon">'+f.icon+"</span><p><b>To "+f.name+"</b><br>via "+match.stop+" · "+lineLabel(match)+'</p><strong class="countdown" data-row-id="'+id+'" data-departure-ms="'+match.departureMs+'">--:--</strong></div>'}).join("");$("transportStatus").textContent=(fromCache?"ⓘ Departures updated locally":"ⓘ Departures updated just now")+" · "+lastStationDiagnostics+" · departures: "+deps.length;updateCountdowns()}

async function fetchPollen(){var vars=(C.pollenTypes||[]).map(function(p){return p.key}).join(",");var url="https://air-quality-api.open-meteo.com/v1/air-quality?latitude="+C.latitude+"&longitude="+C.longitude+"&current="+vars+"&hourly="+vars+"&forecast_days=1&timezone=auto";var r=await fetch(url);if(!r.ok)throw new Error("Pollen API failed");return await r.json()}
function pollenLevel(v){v=Number(v||0);if(v>=80)return{label:"Very High",icon:"🔴",cls:"very-high",rank:4};if(v>=50)return{label:"High",icon:"🟠",cls:"high",rank:3};if(v>=20)return{label:"Moderate",icon:"🟡",cls:"moderate",rank:2};return{label:"Low",icon:"🟢",cls:"low",rank:1}}
function pollenRecommendation(rank){if(rank>=4)return"Limit exposure if you are sensitive.";if(rank>=3)return"Consider antihistamine if sensitive.";if(rank>=2)return"Sunglasses may reduce eye irritation.";return"No special allergy action needed."}
function renderPollen(d){var items=(C.pollenTypes||[]).map(function(p){var v=d.current&&d.current[p.key]!=null?d.current[p.key]:0;var lvl=pollenLevel(v);return{label:p.label,fr:p.fr,value:v,level:lvl}}).sort(function(a,b){return b.level.rank-a.level.rank||b.value-a.value});var global=items[0]?items[0].level:pollenLevel(0);var top=items.filter(function(x){return x.level.rank>1}).slice(0,2);if(!top.length)top=items.slice(0,2);$("pollenSummary").innerHTML='<div class="pollen-level '+global.cls+'">'+global.icon+' Pollen: '+global.label+'</div><div class="pollen-main"><b>Main agents:</b> '+top.map(function(x){return x.label}).join(", ")+'<br><b>Recommendation:</b> '+pollenRecommendation(global.rank)+'</div>';$("pollenDetails").innerHTML=items.map(function(x){return"<div>"+x.label+" ("+x.fr+"): "+x.level.icon+" "+x.level.label+"</div>"}).join("")+"<div>Tip: avoid drying clothes outside on high pollen days.</div>"}
async function loadPollen(){buildConfig();try{var p=await fetchPollen();renderPollen(p)}catch(e){$("pollenSummary").innerHTML='<div class="pollen-main error">Pollen unavailable.</div>'}}
function defaultRoutines(){return[{name:"Office",enabled:true,days:[1,2,3,4,5],items:["Laptop","Badge","Charger"]},{name:"Gym",enabled:true,days:[1,3],items:["Training bag","Shoes","Towel"]},{name:"Pool",enabled:false,days:[2],items:["Swimsuit","Towel","Flip-flops"]},{name:"Groceries",enabled:false,days:[6],items:["Reusable bags"]},{name:"Cycling",enabled:false,days:[1,2,3,4,5],items:["Helmet","Lights","Gloves"]},{name:"Recycling",enabled:false,days:[6],items:["Bottles","Cardboard","Batteries"]},{name:"Post Office",enabled:false,days:[5],items:["Parcel","Return label"]},{name:"Pharmacy",enabled:false,days:[4],items:["Prescription","Insurance card"]},{name:"Weekend hike",enabled:false,days:[6,0],items:["Water","Sunglasses","Power bank"]},{name:"Lunch",enabled:false,days:[1,2,3,4,5],items:["Lunch box","Cutlery"]}]}
function getRoutines(){try{var raw=localStorage.getItem(ROUTINE_KEY);if(raw)return JSON.parse(raw)}catch(e){}var d=defaultRoutines();saveRoutines(d);return d}
function saveRoutines(r){localStorage.setItem(ROUTINE_KEY,JSON.stringify(r))}
function renderTodayRoutines(){var day=new Date().getDay(),active=getRoutines().filter(function(r){return r.enabled&&r.days.indexOf(day)>=0});if(!active.length){$("routineToday").innerHTML='<div class="routine-empty">No recurring items today.</div>';return}$("routineToday").innerHTML=active.slice(0,3).map(function(r){return'<div class="routine-item"><b>'+r.name+'</b><small>'+r.items.join(" · ")+'</small></div>'}).join("")}
function renderRoutineEditor(){var days=["Sun","Mon","Tue","Wed","Thu","Fri","Sat"],r=getRoutines();$("routineList").innerHTML=r.map(function(x,i){return'<div class="routine-row"><input data-i="'+i+'" data-f="name" value="'+x.name+'"><label><input type="checkbox" data-i="'+i+'" data-f="enabled" '+(x.enabled?"checked":"")+'> enabled</label><div class="routine-days">'+days.map(function(d,di){return'<label><input type="checkbox" data-i="'+i+'" data-day="'+di+'" '+(x.days.indexOf(di)>=0?"checked":"")+'> '+d+'</label>'}).join("")+'</div><textarea data-i="'+i+'" data-f="items">'+x.items.join(", ")+'</textarea><br><button data-action="up" data-i="'+i+'">↑</button><button data-action="down" data-i="'+i+'">↓</button><button data-action="delete" data-i="'+i+'">Delete</button></div>'}).join("")}
function commitRoutineEditor(){var r=getRoutines(),inputs=document.querySelectorAll("#routineList input,#routineList textarea");for(var k=0;k<inputs.length;k++){var el=inputs[k],i=Number(el.getAttribute("data-i"));if(isNaN(i)||!r[i])continue;var f=el.getAttribute("data-f");if(f==="name")r[i].name=el.value||"Routine";if(f==="enabled")r[i].enabled=el.checked;if(f==="items")r[i].items=el.value.split(",").map(function(s){return s.trim()}).filter(Boolean)}for(var j=0;j<r.length;j++){var checked=document.querySelectorAll('#routineList input[data-i="'+j+'"][data-day]:checked'),days=[];for(var c=0;c<checked.length;c++)days.push(Number(checked[c].getAttribute("data-day")));r[j].days=days}saveRoutines(r);renderTodayRoutines()}

async function loadWeather(){buildConfig();try{var w=await fetchWeather();renderWeather(w);$("status").textContent=(C.hasPrivateSettings?"Weather updated using private local settings.":"Weather updated using Lausanne center fallback.")}catch(e){$("status").innerHTML='<span class="error">Weather failed: '+e.message+"</span>"}}
async function loadTransport(){buildConfig();try{var stations=await fetchLocationsProgressive(),all=[];for(var i=0;i<Math.min(stations.length,6);i++)try{all=all.concat(await fetchStationboard(stations[i]))}catch(e){}renderTransport(all,false);$("status").textContent="Transport updated. "+lastStationDiagnostics+"; departures: "+lastDepartures.length}catch(e){$("status").innerHTML+=' <span class="error">Transport failed: '+e.message+"</span>";$("transportStatus").textContent="Transport API unavailable."}}
function refreshAll(){loadWeather();loadPollen();loadTransport();renderTodayRoutines()}
$("settingsBtn").onclick=function(){buildConfig();$("setupLat").value=C.hasPrivateSettings?C.latitude:"";$("setupLon").value=C.hasPrivateSettings?C.longitude:"";$("setupRadius").value=C.radiusMeters||500;showSetup($("setupPanel").className.indexOf("hidden")>=0)};
$("saveSetupBtn").onclick=function(){var lat=Number($("setupLat").value),lon=Number($("setupLon").value),radius=Number($("setupRadius").value||500);if(!lat||!lon){$("status").innerHTML='<span class="error">Please enter valid latitude and longitude.</span>';return}savePrivateSettings({placeName:"Home area, Lausanne",latitude:lat,longitude:lon,radiusMeters:radius});showSetup(false);refreshAll()};
$("useFallbackBtn").onclick=function(){localStorage.removeItem(STORAGE_KEY);showSetup(false);refreshAll()};

$("pollenToggle").onclick=function(){var d=$("pollenDetails");d.className=d.className.indexOf("hidden")>=0?"pollen-details":"pollen-details hidden"};
$("routineSettingsBtn").onclick=function(){renderRoutineEditor();$("routineEditor").className="routine-editor"};
$("closeRoutineEditorBtn").onclick=function(){commitRoutineEditor();$("routineEditor").className="routine-editor hidden"};
$("addRoutineBtn").onclick=function(){commitRoutineEditor();var r=getRoutines();r.push({name:"New routine",enabled:true,days:[new Date().getDay()],items:["Item"]});saveRoutines(r);renderRoutineEditor();renderTodayRoutines()};
$("routineList").onclick=function(e){var a=e.target.getAttribute("data-action");if(!a)return;commitRoutineEditor();var i=Number(e.target.getAttribute("data-i")),r=getRoutines();if(a==="delete")r.splice(i,1);if(a==="up"&&i>0){var t=r[i-1];r[i-1]=r[i];r[i]=t}if(a==="down"&&i<r.length-1){var u=r[i+1];r[i+1]=r[i];r[i]=u}saveRoutines(r);renderRoutineEditor();renderTodayRoutines()};
$("refreshBtn").onclick=refreshAll;
buildConfig();updateClock();setInterval(updateClock,30000);if(!C.hasPrivateSettings)showSetup(true);refreshAll();setInterval(loadWeather,(C.weatherRefreshMinutes||30)*60000);setInterval(loadPollen,(C.pollenRefreshMinutes||180)*60000);setInterval(loadTransport,(C.transportRefreshMinutes||3)*60000);setInterval(updateCountdowns,(C.countdownRefreshSeconds||1)*1000);
